---
# ---------------------------------------------------------------------------
# Controller-specific variables
# ---------------------------------------------------------------------------

node_role: controller
