---
# ---------------------------------------------------------------------------
# Worker-specific variables
# ---------------------------------------------------------------------------

node_role: worker
